### PR TITLE
feat: dockerfile image upgrade 1.20 from 1.19

### PR DESCRIPTION
**Pull request by bococ**
feat: dockerfile image upgrade 1.20 from 1.19

### CODE REVIEW

**Review by wastill — APPROVED** [review]
pass

**Review by wastill — APPROVED** [review]
pass

**Comment by wastill** [comment]
@bococ

**Comment by wastill** [comment]
@bococ

**Comment by bococ** [comment]
@wastill

**Review by whg517 — APPROVED** [review]
approve

**Comment by bococ** [comment]
@wastill

**Pull request merged**
